{% set name = "MDAnalysisData" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d9207790f8d265d63db4f55a04d5db19b4507800bd93d9858bf40c8f106729eb

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six
    - setuptools
    - tqdm

test:
  imports:
    - MDAnalysisData

about:
  home: https://github.com/MDAnalysis/MDAnalysisData
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Example MD Simulation Data'
  description: |
    The MDAnalysisData package unifies access to test and example
    trajectories that can be used for workshops and extended tests.
  doc_url: https://www.mdanalysis.org/MDAnalysisData/
  dev_url: https://github.com/MDAnalysis/MDAnalysisData

extra:
  recipe-maintainers:
    - kain88-de
    - orbeckst
    - richardjgowers
